cam_lidar_calib:
  ros__parameters:
    parameters_cam:
      WIDTH: 1920
      HEIGHT: 1080
      FOV: 90
      X: 3.5
      Y: 0
      Z: 0.5
      YAW: 0
      PITCH: 0.0
      ROLL: 0

    parameters_lidar:
      X: 0
      Y: 0
      Z: 0
      YAW: 0
      PITCH: 0
      ROLL: 0
